### ISSUE TITLE
Duplication bug with barrels

### ISSUE THREAD

**Issue by EagL3-GIT** [Mooy1/InfinityExpansion#116] opened 2022-12-15 17:19 UTC
## Description (Required)
two players, u fill the output slot and put the thing u want to duplticate in the middle
one player have to destroy the barrel in the exact time the other player take it out with SHIFT + RMB
the item stays in barrel and also in other player inventory
I mean u can do it also in 1 player but its difficult to do it that fast
(the whole proccess u can see on the video)

## Steps to reproduce the Issue (Required)
- https://cdn.discordapp.com/attachments/606787319583866900/1052972071463944303/dupeglitch2.mp4

## Expected behavior (Required)
- I am not sure, just kinda prevent open it when someone using it at least? (1 player can do it too but hard)

## Server Log / Error Report
- none

## Environment (Required)
Paper git-Paper-307 (MC: 1.19.2)
Slimefun DEV - 1035 (git 0b7c656d)
Metrics-Module #28
Java 17
 
Installed Addons: (12)
Networks vDEV - 45 (git ade6fbd0)
CMILib v1.2.4.1
InfinityExpansion vDEV - 140 (git 0098d2fb)
AureliumSkills vBeta 1.3.11
ShopGUIPlus v1.80.1
LiteXpansion vDEV - 182 (git d3800398)
WestCore v1.2-SNAPSHOT
Residence v5.1.0.1
FluffyMachines vDEV - 127 (git cf047dcf)
CMI v9.2.6.1
ItemsAdder v3.3.0-beta-r11
HeadLimiter v23

**Comment by Sefiraat** [comment] 2022-12-15 17:21
You mentioned in the previous issue that you can do this with all slimefun gui machines and I did mention that this is a very important factor here as that is the difference between this being a slimefun issue and an infinity expansion issue. Please edit the detail of the call the machines you have been able to do this with and then amend the title of the issue as appropriate. If this call is left as-is without this the next person to come along may be likely to just close it

**Comment by EagL3-GIT** [comment] 2022-12-15 19:46
The thing is that I am not sure if it happens only with storages from infinity expansion (barrels) cause its not that easy to do it in the same time with other guy, my thoughts are it may happen with blocks that are able to hold items inside them after break.

**Comment by Sefiraat** [comment] 2022-12-15 22:21
That differentiation is very important here as it’s the difference between this issue belonging on this repo or belonging to another repo. For now I will give the benefit of the doubt as you have said you achieved the same results on other slimefun machines, if you could please test and confirm this (I would but I’m not near my machine for a while) and if it is confirmed we can change the description and title to something more suitable, otherwise it’s needs to be redirected. Thanks

**Comment by EagL3-GIT** [comment] 2022-12-15 22:37
There is no such a machine in slmefun gui which stores items inside after break up, so its not even possible to test it on "default" slimefun

**Comment by EagL3-GIT** [comment] 2022-12-15 22:39
Anyways this is a known bug for a long time if u check old posts: https://github.com/Mooy1/InfinityExpansion/issues/114

**Comment by 69Slowpoke** [comment] 2023-01-13 15:23
Hi Sefi, 

Is there any update about this bug? I tested this bug with other storages for you but no the infinity expansion storage was the only one who made me dupe. This together with the other SF dupe makes it rain abuse on the servers from keys to cosmetics. 

I tried it with the Quantum storage but no effect. 
If there is anything I can do regarding testing to help let me know.

**Comment by IamGlu10** [comment] 2023-01-13 17:33
Actually poke, there are multiple dupes on your server and not only that but there are some very poorly configured plugins and permissions so maybe you should get started on fixing those first.

**Comment by 69Slowpoke** [comment] 2023-01-13 17:36
I know there are multiple with backpacks/storages/shulkers and all kinds of crazy silly stuff (danktech too) but this one is far the most used one when we bust people on duping sadly. 

Imo there is no way to prevent any abuse anyway, from hacks to duping but thats a different discussion. This one is far most used (sadly) probs because its so "cheap" to do so.

**Comment by IamGlu10** [comment] 2023-01-13 17:51
Fun fact:
This addon isn't responsible for the dupe alone, it's the combination of this addon which another one that you (and some others in the issues sections) use. You can prevent this dupe just by changing values in configs. 
Good luck on figuring this out, adiós

**Closed** 2023-07-07 22:03 UTC
Labels: bug
